name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: ellis-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build the Docker image
      working-directory: ./ellis
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
    
    - name: Test the Docker image
      run: |
        docker run -d --name ellis-test -p 8000:8000 ${{ env.IMAGE_NAME }}:latest
        sleep 15
        
        # Verificar se o container está rodando
        docker ps | grep ellis-test
        
        # Verificar se a API está respondendo
        timeout 30 bash -c 'until curl -f http://localhost:8000/docs; do sleep 2; done'
        
        # Cleanup
        docker stop ellis-test
        docker rm ellis-test
    
    - name: List Docker images
      run: docker images | grep ${{ env.IMAGE_NAME }}
